/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAavePool__factory } from "./IAavePool__factory";
export { IERC20Minimal__factory } from "./IERC20Minimal__factory";
