/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IronShieldExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AERODROME_ROUTER"
      | "UNISWAP_V3_ROUTER"
      | "aavePool"
      | "blacklistToken"
      | "blacklisted"
      | "executeOperation"
      | "initiateArbitrage"
      | "minProfitWei"
      | "owner"
      | "paused"
      | "removeBlacklist"
      | "setMinProfit"
      | "setPaused"
      | "totalExecutions"
      | "totalProfit"
      | "weth"
      | "withdrawETH"
      | "withdrawProfit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitrageExecuted"
      | "EmergencyPause"
      | "MinProfitUpdated"
      | "ProfitWithdrawn"
      | "TokenBlacklisted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AERODROME_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNISWAP_V3_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blacklistToken",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateArbitrage",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minProfitWei",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinProfit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "totalExecutions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalProfit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProfit",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AERODROME_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNISWAP_V3_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateArbitrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minProfitWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalExecutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProfit",
    data: BytesLike
  ): Result;
}

export namespace ArbitrageExecutedEvent {
  export type InputTuple = [
    token: AddressLike,
    loanAmount: BigNumberish,
    profit: BigNumberish,
    gasUsed: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    loanAmount: bigint,
    profit: bigint,
    gasUsed: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    loanAmount: bigint;
    profit: bigint;
    gasUsed: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinProfitUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBlacklistedEvent {
  export type InputTuple = [token: AddressLike, reason: string];
  export type OutputTuple = [token: string, reason: string];
  export interface OutputObject {
    token: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IronShieldExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IronShieldExecutor;
  waitForDeployment(): Promise<this>;

  interface: IronShieldExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AERODROME_ROUTER: TypedContractMethod<[], [string], "view">;

  UNISWAP_V3_ROUTER: TypedContractMethod<[], [string], "view">;

  aavePool: TypedContractMethod<[], [string], "view">;

  blacklistToken: TypedContractMethod<
    [token: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  blacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  executeOperation: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  initiateArbitrage: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, swapData: BytesLike],
    [void],
    "nonpayable"
  >;

  minProfitWei: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  removeBlacklist: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinProfit: TypedContractMethod<
    [_minProfitWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  totalExecutions: TypedContractMethod<[], [bigint], "view">;

  totalProfit: TypedContractMethod<[], [bigint], "view">;

  weth: TypedContractMethod<[], [string], "view">;

  withdrawETH: TypedContractMethod<[], [void], "nonpayable">;

  withdrawProfit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AERODROME_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UNISWAP_V3_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "blacklistToken"
  ): TypedContractMethod<
    [token: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeOperation"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiateArbitrage"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, swapData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minProfitWei"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeBlacklist"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinProfit"
  ): TypedContractMethod<[_minProfitWei: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalExecutions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalProfit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProfit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArbitrageExecuted"
  ): TypedContractEvent<
    ArbitrageExecutedEvent.InputTuple,
    ArbitrageExecutedEvent.OutputTuple,
    ArbitrageExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "MinProfitUpdated"
  ): TypedContractEvent<
    MinProfitUpdatedEvent.InputTuple,
    MinProfitUpdatedEvent.OutputTuple,
    MinProfitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfitWithdrawn"
  ): TypedContractEvent<
    ProfitWithdrawnEvent.InputTuple,
    ProfitWithdrawnEvent.OutputTuple,
    ProfitWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TokenBlacklisted"
  ): TypedContractEvent<
    TokenBlacklistedEvent.InputTuple,
    TokenBlacklistedEvent.OutputTuple,
    TokenBlacklistedEvent.OutputObject
  >;

  filters: {
    "ArbitrageExecuted(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ArbitrageExecutedEvent.InputTuple,
      ArbitrageExecutedEvent.OutputTuple,
      ArbitrageExecutedEvent.OutputObject
    >;
    ArbitrageExecuted: TypedContractEvent<
      ArbitrageExecutedEvent.InputTuple,
      ArbitrageExecutedEvent.OutputTuple,
      ArbitrageExecutedEvent.OutputObject
    >;

    "EmergencyPause(bool)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "MinProfitUpdated(uint256,uint256)": TypedContractEvent<
      MinProfitUpdatedEvent.InputTuple,
      MinProfitUpdatedEvent.OutputTuple,
      MinProfitUpdatedEvent.OutputObject
    >;
    MinProfitUpdated: TypedContractEvent<
      MinProfitUpdatedEvent.InputTuple,
      MinProfitUpdatedEvent.OutputTuple,
      MinProfitUpdatedEvent.OutputObject
    >;

    "ProfitWithdrawn(address,uint256)": TypedContractEvent<
      ProfitWithdrawnEvent.InputTuple,
      ProfitWithdrawnEvent.OutputTuple,
      ProfitWithdrawnEvent.OutputObject
    >;
    ProfitWithdrawn: TypedContractEvent<
      ProfitWithdrawnEvent.InputTuple,
      ProfitWithdrawnEvent.OutputTuple,
      ProfitWithdrawnEvent.OutputObject
    >;

    "TokenBlacklisted(address,string)": TypedContractEvent<
      TokenBlacklistedEvent.InputTuple,
      TokenBlacklistedEvent.OutputTuple,
      TokenBlacklistedEvent.OutputObject
    >;
    TokenBlacklisted: TypedContractEvent<
      TokenBlacklistedEvent.InputTuple,
      TokenBlacklistedEvent.OutputTuple,
      TokenBlacklistedEvent.OutputObject
    >;
  };
}
